### PR TITLE
Add method close to InfluxDBClient class.

### PR DESCRIPTION
**Pull request by Linux-oiD**
This method just closes session if it's exist.
#459

### CODE REVIEW

**Comment by sebito91** [comment]
@Linux-oiD this seems fine, but could you please squash to one commit?

@aviau UPDATE REQUESTED

**Comment by aviau** [comment]
I can actually squash this using github.

**Comment by Linux-oiD** [comment]
@sebito91 @aviau I've merged current master to this branch. You can squash changes into one commit during merge.

**Comment by aviau** [comment]
Thanks <3

**Pull request merged**
