### PR TITLE
Fix #828 "Context manager for InfluxDBClient not working correctly?"

### LINKED ISSUE #828: Context manager for InfluxDBClient not working correctly?
- **InfluxDB version:** 1.8.0
- **InfluxDB-python version:** 5.3.0
- **Python version:** 3.6.8
- **Operating system version:** CentOS 7 x86_64

With #816 support for context managers has been added to InfluxDBClient. I am currently trying to use it, but it seems not to work:
```python
with influxdb.InfluxDBClient(host='host', port=8086, database='db') as client:
    client.write_points(json_body)
```

It fails, as client is `None`:
```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    client.write_points(json_body)
AttributeError: 'NoneType' object has no attribute 'write_points'
```

Looking at the source, the `__enter__` function does not return any object, just a pass:
https://github.com/influxdata/influxdb-python/blob/28a30987a9dc2e24dbcf1100d2ae9e48883313bc/influxdb/client.py#L172-L174

Should this not return the client object, e.g.:
```python
 def __enter__(self): 
     """Enter function as used by context manager.""" 
     return self
```

Or am I incorrectly using the context manager with influxdb?

### PR DESCRIPTION
**Pull request by antimirov**
Fixed it by returning a client instance from __ enter __

---
##### Contributor checklist

- [X] Builds are passing
- [] New tests have been added (for feature additions)

### CODE REVIEW

**Comment by antimirov** [comment]
Hm, the CI error seems to be unrelated to the commit. Can it be triggered to re-run?

**Comment by vancromy** [comment]
@aviau @sebito91 Would it be possible to review this. Doesn't look like a harmful change and as is although the documentation boasts the feature of context managers it is not right. As is today the client does not work as a context manager... Either fix the code or change the documentation :)

**Comment by Ramshield** [comment]
@aviau @sebito91 Anything I can do to help?

**Comment by russorat** [comment]
@antimirov just sign the CLA form and I will merge this. https://www.influxdata.com/legal/cla/#license-agreement

**Comment by antimirov** [comment]
@russorat I've signed it, please proceed

**Review by russorat — APPROVED** [review]
LGTM

**Pull request merged**
