### PR TITLE
add '' to categorical columns if not already in categories

### PR DESCRIPTION
**Pull request by omki2005**
Fix for issue #504

### CODE REVIEW

**Comment by omki2005** [comment]
This fixes the issue that I had raised.

**Comment by xginn8** [comment]
@omki2005 would you mind adding a test to make sure this transformation is properly applied?

**Comment by omki2005** [comment]
Hi xginn8, I'm a bit new to github. What exactly did you do when you did "Merge branch 'master' into master" ?

**Comment by xginn8** [comment]
@omki2005 all that means is that i merged `master` back into your branch, to keep it in sync.

**Comment by sebito91** [comment]
@omki2005 is this still required? If not I'd like to close this for now.

**Comment by omki2005** [comment]
Hey @sebito91 
I've long since moved on to other projects. I don't use this project anymore. We can close this issue if no one else is facing the same problem.
Thanks guys!

**Pull request closed without merging**
