### PR TITLE
move use_udp and udp_port private

### LINKED ISSUE #241: InfluxDBClient: Access to connection parameters
The most of connection parameters (ex: host, port, etc.) are declared private. Instead some others (`use_udp` and `use_port`) are public (see below):

`self._verify_ssl = verify_ssl`

`self.use_udp = use_udp`
`self.udp_port = udp_port`
`self._session = requests.Session()`

Why this difference?

### PR DESCRIPTION
**Pull request by sebito91**
Fixes #241

### CODE REVIEW

**Comment by sebito91** [comment]
@aviau READY TO MERGE

**Comment by aviau** [comment]
I'd like a property for transition please <3

**Comment by sebito91** [comment]
@aviau added fixup for this, will squash when you approve.

**Comment by aviau** [comment]
Would you like to merge yourself? ;)

**Comment by sebito91** [comment]
Yes, yes I would :D

**Comment by sebito91** [comment]
Can't review my own PR, if you would be so kind please @aviau?

**Pull request merged**
