### PR TITLE
Add CQs management methods to the client

### PR DESCRIPTION
**Pull request by smolse**
This PR adds to the client new methods which allow create, show and drop continuous queries in InfluxDB more easily.

### CODE REVIEW

**Comment by smolse** [comment]
@aviau seems like docs test is really broken.

**Comment by aviau** [comment]
>  seems like docs test is really broken.

Yeah. Somebody needs to fix it.

**Comment by aviau** [comment]
Can you rebase this on master? The tests should now pass.

**Comment by smolse** [comment]
Yay, it is passing now.

**Comment by sebito91** [comment]
@smolse the logic here is completely fine, but can you please add comments to the test functions (something basic)? We've introduced PEP257 compliance over the past few weeks, and that's the only failing test at the moment.

Once you've added, we can merge this.

**Comment by lukaszdudek-silvair** [comment]
@smolse - do you intend to work on this anytime soon?
AFAIU the thing to be done (apart from rebasing on `master` again) is to add docstrings to test cases - is that right, @sebito91 ?

**Pull request merged**
