### PR TITLE
chore(line_protocol): fix nanosecond timestamp resolution for points

### LINKED ISSUE #340: dataframe client precision "ns" causing round error
It appears, that the line,
_dataframe_client.py:145 
             'time': int(ts.value / precision_factor)

Is causing a time rounding error when precision_factor is 'ns'. It is likely to be insufficient precision in the double64 type to hold this many seconds (inc 9 decimal places). The rounding error is in the order of (<100ns). This is consistent with the 15 sig.figures of the double64.

The issue is not present when using the line without the division e.g.:
             'time': ts.value

but only for precision_factor, None or 'ns'. Other precisions (unsurprisingly) create time out of bounds on the POST to influxdb.

This line was added at commit:
https://github.com/influxdata/influxdb-python/commit/02ddf0e783d57762341fbf0662ac3b6c9696dcbc

### LINKED ISSUE #344: Timestamps slightly different in Influxdb
Occasionally my data arrives in the database with timestamps that are ever so slightly ahead or behind the time they actually should be, and I have been having trouble tracking down where this behavior is coming from!

I am using a pandas dataframe with a datetime index, which is being written to the database using [write_points](https://github.com/influxdata/influxdb-python/blob/master/influxdb/client.py#L352) (No specified time precision). The timestamps within the dataframe are numpy datetime64[ns]'s and Influx's default time precision is also nanoseconds iirc. What often happens though is that the timestamps in the database are slightly different and looks like it possibly has to do with floats? (My problem is similar to [this](https://groups.google.com/forum/#!topic/influxdb/uyp1kmMXwxI), as queries based on time now miss 1 or 2 data points)

For instance, this is how the following timestamps change:

datetime64[ns]                              -->         unix timestamp in Influxdb
2016-06-20 13:35:42.270000       -->        1466429742270000128
2016-06-20 14:02:49.770000       -->        1466431369769999872

If anyone could clarify why this behavior is happening or point me in the right direction of how to fix it, that would be greatly appreciated, thanks!

Edit: After glancing at the other possible issues, it may very well be related to [Issue 340](https://github.com/influxdata/influxdb-python/issues/340)

### LINKED ISSUE #489: Nanoseconds not being written correctly to DB (last few digits get changed)
In the write_points function with json protocol and time_precision = 'n'.

There is a line in the code (line # 217 in version 4.1.1 - see snippet below ) that basically takes a datetime value and divided it by 1. However the division is done using float (/) versus integer division (//). This changes the last few digits of the datetime being written. E.g. it the value 1502114400290050489 when divided by 1 using / changes to 1.5021144002900506e+18. When using // and dividing by 1 it remains unchanged.

------------CODE COPY BELOW------------------------------------
        points = [
            {'measurement': measurement,
             'tags': dict(list(tag.items()) + list(tags.items())),
             'fields': rec,
             **_'time': int(ts.value / precision_factor)}_**
            for ts, tag, rec in zip(dataframe.index,
                                    dataframe[tag_columns].to_dict('record'),
                                    dataframe[field_columns].to_dict('record'))

### LINKED ISSUE #527: Cannot work with nanosecond precision
Influx is designed to work with nanosecond precision. Therefore, the timestamp is stored as a 64 bit unsigned Integer internally (And system max time is kind of Long.MAX in terms of Java speak). 

Python, as we know, has no nanosecond support for it's `datetime` objects.
Numpy's datetime64, on the other side, works nicely with nanosecond precision date objects.

If I now create a dataframe like this:
```
                               value
time                                
1970-01-01 00:00:00.000000001     40
2017-06-01 00:00:00.000000000    100
2017-06-10 13:13:13.123456789    150
```
and call within the DataFrameClient `_convert_dataframe_to_lines`, I'll end up with
```
['myMeasurement value=40i 1', 'myMeasurement value=100i -432406528', 'myMeasurement value=150i 501012992']
```
See how the timestamp is correct only for the first entry.

Another bug appears when using json format instead:
```
[{'measurement': 'myMeasurement', 'tags': {}, 'fields': {'value': 40}, 'time': 1}, {'measurement': 'myMeasurement', 'tags': {}, 'fields': {'value': 100}, 'time': 1496275200000000000}, {'measurement': 'myMeasurement', 'tags': {}, 'fields': {'value': 150}, 'time': 1497100393123456768}]
```
See how for the last value, the last nanosecond precision is truncated. 

In order to write data via DataFrameClient, I sadly have to use a python datetime format and cannot go for an int or something as time column directly due to type checks.

---

In InfluxDBClient docu for write_points, you write that `:param time_precision: Either 's', 'm', 'ms' or 'u', defaults to None` even though in the code, you also allow for `n`. 

I didn't test out the InfluxDBClient directly for writing, but for a short glance on the code (looking at `_convert_timestamp`, especially at `ns = (timestamp - EPOCH).total_seconds() * 1e9`, it doesn't look like it is supporting nanosecond or even something more than second precision either. 

*EDIT* Just to let you know, I have used influxdb==4.1.1 in my requirements.txt file and I'm running the code with Python 3.6.

### LINKED ISSUE #649: Incorrect nanosecond timestamps being written to influxdb
Writing point with time precision  in ns results in incorrect nanosecond timestamps being written to influxdb
effect can be noticed in writing points from both the  `DataFrameClient.writepoints`as well as the `InfluxDBClient.write`
This has been noted in issues: #527,#489, #346 and #344 and #340 

  and a proposed pull request submitted. [https://github.com/influxdata/influxdb-python/pull/346](https://github.com/influxdata/influxdb-python/pull/346) .  I believe this pull request does not go far enough

#489 describes the same "floor divide" solution as part of the solution being proposed here. 

This solution I am proposing in a pull request will use, floor divide and  pandas.Timestamp that supports ns resolution.

### Implication
In trying to use the library to update a record it writes a new record with the erroneous timestamp

### Effected code regions
`_dataframe_client` 
   _convert_dataframe_to_json
   _convert_dataframe_to_lines
   _datetime_to_epoch
`line_protocol.py`  
  _convert_timestamp

### Explanation:
the divide of an (np.int64 or int ) nanosecond timepoint by 1 (ns precision)  is producing errors. it is necessary to use the floor divide operator // which yields the correct (np.int64 or int) value

If an np.int64 is divided (Operator /)  by an int  it yields a float64. When the initial  np.int64 value is large enough the conversion  back to an np.int64 looses nanosecond precision. The same error occurs with standard python int types.

### Example (formulated in a ipython notebook)

    .......... dataframe  is from a query (influxdb measurement having particular field value errors) returned 2 timepoints
    dataframe.index  --->   DatetimeIndex(['2018-05-29 00:53:12.889962156+00:00', '2018-10-03 07:06:36.975643599+00:00'], dtype='datetime64[ns, UTC]', freq=None)
    dataframe.index[1]  ---> Timestamp('2018-10-03 07:06:36.975643599+0000', tz='UTC')
    dataframe.index[1].value  ---> 1538550396975643599
    
    ######    alternative method for timepoint fabrication   #########
    timepoint = pd.Timestamp('2018-10-03 07:06:36.975643599+0000', tz='UTC')
    timepoint.value   ---> 1538550396975643599

    type(timepoint.value)   ---> int
    timepoint.value / 1  ----> 1.5385503969756436e+18
    type(timepoint.value / 1) ----> float
    type(timepoint.value // 1) ----> int
    np.int64(timepoint.value // 1)   ---> 1538550396975643599
    np.int64(timepoint.value / 1)  ---> 1538550396975643648

Error(ns) is 

    np.int64(timepoint.value // 1) - np.int64(timepoint.value / 1)  ---> -49

######## Check using unit test timepoint  ################

    EPOCH = pd.Timestamp('1970-01-01 00:00+00:00')
    nowplus1h = EPOCH + pd.Timedelta('1 hour')
    nowplus1h.value ---> 3600000000000
    nowplus1h.value / 1 ---> 3600000000000.0
    np.int64(nowplus1h.value / 1) ---> 3600000000000

No Error in this 

######### Suggested  unit test timepoint  ################

    futuretimepoint = EPOCH + pd.Timedelta('20000 day  +23:10:55.123456789')
    futuretimepoint.value ---> 1728083455123456789
    futuretimepoint.value / 1 ---> 1.7280834551234568e+18
    np.int64(futuretimepoint.value / 1) ---> 1728083455123456768

Error(ns) is

    futuretimepoint.value - np.int64(futuretimepoint.value / 1) ---> 21

  

all locations where timepoints are calculated need modification to yield the expected result in nanosecond precision
the unittests do not show this up as the 2 test timepoints are small enough to not show the loss of precision
points are EPOCH  '1970-01-01 00:00+00:00'   EPOCH + 1 hour.   These 2 test points have only microsecond resolution with no nano second component.
I propose the test case  2  to be something like  EPOCH + 20000days and 23h 10m 55.123456789s. It is necessary to change all calculations based on datetime (only has microsecond resolution)  to pandas Timedelta and Timestamp (these have nanosecond resolution)

I am preparing a pull request that attempts to address all timestamp calculations and fixes the unittests

Product version where issue discovered and where fixes are being tested

    pd.show_versions()
    INSTALLED VERSIONS
    ------------------
    commit: None
    python: 3.6.2.final.0
    python-bits: 64
    OS: Windows
    OS-release: 10
    machine: AMD64
    processor: Intel64 Family 6 Model 70 Stepping 1, GenuineIntel
    byteorder: little
    LC_ALL: None
    LANG: None
    LOCALE: None.None

    pandas: 0.20.3
    pytest: None
    pip: 9.0.1
    setuptools: 36.4.0
    Cython: None
    numpy: 1.13.1
    scipy: 0.19.1
    xarray: None
    IPython: 6.2.1
    sphinx: None
    patsy: None
    dateutil: 2.6.1
    pytz: 2017.2
    ............................................
    ...........
    ..........................

np.version.full_version

### PR DESCRIPTION
**Pull request by sebito91**
Closes #407.
Closes #650. 
Closes #649. 
Closes #527.
Closes #489. 
Closes #346. 
Closes #344.
Closes #340.

This PR merges work done in #407 into the current master without inclusion of external requirements (e.g. `pandas`). Thanks to @AndreCAndersen and @clslgrnc !

### CODE REVIEW

**Comment by inselbuch** [comment]
rockstars!

**Comment by sebito91** [comment]
Please let me know if it's _not_ working and we'll get it fixed. Release `v5.2.4` set to come out Friday, April 10th, 2020.

**Comment by clslgrnc** [comment]
Should release v5.2.4 come with a warning in the unusual case where someone tries to access a point inserted with v5.2.3 from its timestamp?

As an example if I insert a point every millisecond, some are inserted with a wrong timestamp, but it might not be an issue because when I try to retrieve a point at a given timestamp the same error is made and I retrieve the right point. Migrating to v5.2.4 the error is not made anymore and influxdb would return no points at the requested (correct) millisecond (because the actual point is slightly off).

I agree that this is a corner case and probably not how people should use influxdb.

**Comment by cuxcrider** [comment]
Hi all,

Thank you for continuing to work on this. 

I am finding potentially two issues:
1) (minor)  I can confirm I can read in nanosecond timestamps with the dataframe client but only if I specify epoch = 'ns'.  If I do not specify epoch I get microsecond precision.  I believe this is contrary to the documentation that says nanosecond is the default.

2) (more troublesome)  The dataframe client will write a nanosecond timestamp, but if there is a timestamp that is within a few hundred nanoseconds it seems to think it is the same timestamp and does not write the additional datapoint.  This is strange to me because I do not remember this behavior after some discussions with contributors on #649 , but now if you run my code I posted in #649 you will see that you only get two data points rather than all four.  I have tried running Pandas 1.1.2 and 0.23.4 with the same results.  I am on Numpy 1.19.1, Python 3.7.9, and Influxdb-python 5.3.0.  If you change timestamp '2019-10-04 06:27:19.850557111+00:00' to  '2019-10-04 06:27:19.850555111+00:00' then the datapoint is written.  

Any thoughts?

Here is my example code you can use to demonstrate the result, just enter in your user, password, host-ip and database name:

```
from influxdb import InfluxDBClient, DataFrameClient
import numpy as np
import pandas as pd
pd.show_versions()

#I use this make sure I write to influxdb anything that is a number as a float
def df_int_to_float(df):
    try:
        for i in df.select_dtypes('number').columns.values:
            df[i] = df[i].astype('float64')
    except:
        print('cycle not in dataframe')
    return df

###remember to enter your host, user, and password
def main(host = , port='8086'):
    """Instantiate a connection to the InfluxDB."""
    
    user = 
    password = 
    db_name = 
    client = InfluxDBClient(host, port, user, password)
    client.drop_database(db_name) 
    client.create_database(db_name)
    dfclient = DataFrameClient(host, port, user, password, db_name)
            
    for_df_dict = {"nanFloats": [1.1, float('nan') , 3.3, 4.4], "onlyFloats": [1.1, 2.2, 3.3, 4.4], 
                                  "strings":['one_one', 'two_two' ,'three_three', 'four_four']}
    df = pd.DataFrame.from_dict(for_df_dict)
    df['time'] = ['2019-10-04 06:27:19.850557111+00:00', '2019-10-04 06:27:19.850557184+00:00', '2019-10-04 06:27:42.251396864+00:00',
      '2019-10-04 06:27:42.251396974+00:00']
    df['time'] = pd.to_datetime(df['time'], unit='ns')
    df = df.set_index('time')
    df = df_int_to_float(df) 
    #####  df_types just for informational purposes
    df_types_float = df.select_dtypes(include = ['float64']) 
    df_types_bool = df.select_dtypes(include = ['bool'])
    df_types_obj = df.select_dtypes(include = ['object'])
    ########
    dfclient.write_points(df, 'test', time_precision='n')  
    df_dict = dfclient.query('SELECT * FROM \"test\" ', epoch = 'ns')
    
    

if __name__ == '__main__':
    main()
```

**Comment by lihaoml** [comment]
> Hi all,
> 
> Thank you for continuing to work on this.
> 
> I am finding potentially two issues:
> 
> 1. (minor)  I can confirm I can read in nanosecond timestamps with the dataframe client but only if I specify epoch = 'ns'.  If I do not specify epoch I get microsecond precision.  I believe this is contrary to the documentation that says nanosecond is the default.
> 2. (more troublesome)  The dataframe client will write a nanosecond timestamp, but if there is a timestamp that is within a few hundred nanoseconds it seems to think it is the same timestamp and does not write the additional datapoint.  This is strange to me because I do not remember this behavior after some discussions with contributors on #649 , but now if you run my code I posted in #649 you will see that you only get two data points rather than all four.  I have tried running Pandas 1.1.2 and 0.23.4 with the same results.  I am on Numpy 1.19.1, Python 3.7.9, and Influxdb-python 5.3.0.  If you change timestamp '2019-10-04 06:27:19.850557111+00:00' to  '2019-10-04 06:27:19.850555111+00:00' then the datapoint is written.
> 
> Any thoughts?
> 
> Here is my example code you can use to demonstrate the result, just enter in your user, password, host-ip and database name:
> 
> ```
> from influxdb import InfluxDBClient, DataFrameClient
> import numpy as np
> import pandas as pd
> pd.show_versions()
> 
> #I use this make sure I write to influxdb anything that is a number as a float
> def df_int_to_float(df):
>     try:
>         for i in df.select_dtypes('number').columns.values:
>             df[i] = df[i].astype('float64')
>     except:
>         print('cycle not in dataframe')
>     return df
> 
> ###remember to enter your host, user, and password
> def main(host = , port='8086'):
>     """Instantiate a connection to the InfluxDB."""
>     
>     user = 
>     password = 
>     db_name = 
>     client = InfluxDBClient(host, port, user, password)
>     client.drop_database(db_name) 
>     client.create_database(db_name)
>     dfclient = DataFrameClient(host, port, user, password, db_name)
>             
>     for_df_dict = {"nanFloats": [1.1, float('nan') , 3.3, 4.4], "onlyFloats": [1.1, 2.2, 3.3, 4.4], 
>                                   "strings":['one_one', 'two_two' ,'three_three', 'four_four']}
>     df = pd.DataFrame.from_dict(for_df_dict)
>     df['time'] = ['2019-10-04 06:27:19.850557111+00:00', '2019-10-04 06:27:19.850557184+00:00', '2019-10-04 06:27:42.251396864+00:00',
>       '2019-10-04 06:27:42.251396974+00:00']
>     df['time'] = pd.to_datetime(df['time'], unit='ns')
>     df = df.set_index('time')
>     df = df_int_to_float(df) 
>     #####  df_types just for informational purposes
>     df_types_float = df.select_dtypes(include = ['float64']) 
>     df_types_bool = df.select_dtypes(include = ['bool'])
>     df_types_obj = df.select_dtypes(include = ['object'])
>     ########
>     dfclient.write_points(df, 'test', time_precision='n')  
>     df_dict = dfclient.query('SELECT * FROM \"test\" ', epoch = 'ns')
>     
>     
> 
> if __name__ == '__main__':
>     main()
> ```

I got the same issue here with v5.3.0 and v5.2.3

I think the bug is in _dataframe_client.py:

replacing 
time = ((dataframe.index.to_timestamp().values.astype(np.int64) / precision_factor).astype(np.int64).astype(str))

with
time = ((dataframe.index.to_timestamp().values.astype(np.int64) // precision_factor).astype(np.int64).astype(str))

fixes the issue for me. 

Not a python expert, but it looks like in python3   int/int = float

**Pull request merged**
