### PR TITLE
add consistency parameter to write_points

### PR DESCRIPTION
**Pull request by RonRothman**
This PR adds a `consistency` parameter to `InfluxDBClient.write_points`.

Motivated by this issue: https://github.com/influxdata/influxdb-python/issues/643.

### CODE REVIEW

**Comment by aviau** [comment]
Great! I'd merge this if the tests were not broken. Someone has to fix the tests.

**Comment by RonRothman** [comment]
Thanks @aviau!

Just checking - you mean the preexisting test framework, right? Not [necessarily] the particular tests I added?

**Comment by xginn8** [comment]
@RonRothman some of these failures look unrelated to your change. I will try to fix those generally asap.

**Comment by RonRothman** [comment]
Got it-- thanks.

**Comment by aviau** [comment]
> you mean the preexisting test framework, right?

Yes exactly! Your code looks perfectly fine.

**Comment by xginn8** [comment]
@RonRothman sorry for the delay, I believe https://github.com/influxdata/influxdb-python/pull/674 should fix the issue. Once that gets merged, we'll retest this and merge if it looks good. Thanks for contributing!

**Comment by xginn8** [comment]
@RonRothman if you are able to fix up the failing linting tests, this PR looks ready to merge. Thanks for contributing!

**Comment by RonRothman** [comment]
@xginn8 Thanks! Done.

**Pull request merged**
