### PR TITLE
Specify Retention Policy in SeriesHelper

### PR DESCRIPTION
**Pull request by csanz91**
I have added an option in the SeriesHelper meta options to be able to write the data with a custom retention policy.

This request was previously commented in this issue: #300

### CODE REVIEW

**Comment by xginn8** [comment]
Hi @csanz91 please ensure that all the tests are passing in Travis, and then we can take a look

**Comment by csanz91** [comment]
All tests are passing now. Feel free to review the pull request.

**Comment by xginn8** [comment]
Hi @csanz91 and thanks for submitting this patch! The implementation looks fine, but please add some tests to ensure this feature functions properly. You'll want to look here: https://github.com/influxdata/influxdb-python/blob/master/influxdb/tests/helper_test.py

**Comment by csanz91** [comment]
I have added a couple of tests in which I check the args passed to the "write_points" function to look for the specified retention policy. I also have a case without a retention policy to make sure I'm not altering the default rp.

**Pull request merged**
