### PR TITLE
Rename all mixedCase globals to snake case to appease N816

### PR DESCRIPTION
**Pull request by xginn8**
Signed-off-by: Matthew McGinn <mamcgi@gmail.com>

### CODE REVIEW

**Comment by clslgrnc** [comment]
You forgot the test cases:
influxdb-python/influxdb/tests/server_tests/client_test_with_server.py
influxdb-python/influxdb/tests/__init__.py

**Comment by clslgrnc** [comment]
You can ignore my now deleted previous message, the following line remains:
https://github.com/influxdata/influxdb-python/blob/c9c7fa0f561f147913529581be43b8dc33afe168/influxdb/tests/__init__.py#L15
https://github.com/influxdata/influxdb-python/blob/c9c7fa0f561f147913529581be43b8dc33afe168/influxdb/tests/server_tests/client_test_with_server.py#L26
https://github.com/influxdata/influxdb-python/blob/c9c7fa0f561f147913529581be43b8dc33afe168/influxdb/tests/server_tests/client_test_with_server.py#L93

Or not I see you just pushed something
https://github.com/influxdata/influxdb-python/blob/c9c7fa0f561f147913529581be43b8dc33afe168/influxdb/tests/server_tests/client_test_with_server.py#L123
https://github.com/influxdata/influxdb-python/blob/c9c7fa0f561f147913529581be43b8dc33afe168/influxdb/tests/server_tests/client_test_with_server.py#L296
https://github.com/influxdata/influxdb-python/blob/c9c7fa0f561f147913529581be43b8dc33afe168/influxdb/tests/server_tests/client_test_with_server.py#L410-L412
https://github.com/influxdata/influxdb-python/blob/c9c7fa0f561f147913529581be43b8dc33afe168/influxdb/tests/server_tests/client_test_with_server.py#L418
https://github.com/influxdata/influxdb-python/blob/c9c7fa0f561f147913529581be43b8dc33afe168/influxdb/tests/server_tests/client_test_with_server.py#L424

**Comment by xginn8** [comment]
Sorry about that, missed a stashed change set. @clslgrnc PTAL

**Comment by clslgrnc** [comment]
looks good to me (and travis)

**Pull request merged**
