### PR TITLE
Add support for shard duration in retention policies

### PR DESCRIPTION
**Pull request by oldmantaiter**
- SHARD DURATION was added in 45b3e61, this adds support to the python
  client so it can be modified/added

### CODE REVIEW

**Comment by aviau** [comment]
Can you please rebase your PR? (or just merge master in your branch)

(please GitHub, give me a rebase button like Gerrit)

**Comment by aviau** [comment]
Can you please fix the corresponding tests?

**Comment by oldmantaiter** [comment]
@aviau Yep.

**Comment by sebito91** [comment]
@oldmantaiter any chance you could please rebase with master and test? This looks solid, and is a good catch.

@aviau this looks good to me, ready to merge.

**Comment by oldmantaiter** [comment]
Wow, missed this update entirely. I'll see what I can do @sebito91 - I'm not using this library anymore so I'll need to do a bit of catchup.

**Comment by oldmantaiter** [comment]
My apologies for not getting back into this, I’ll close this.

**Pull request closed without merging**
