### PR TITLE
Fix testsuite

### PR DESCRIPTION
**Pull request by babilen**
These commits fix some of the errors in the testsuite and mostly concern unicode handling and retention policy tests.

### CODE REVIEW

**Comment by aviau** [comment]
It seems like the test have failed due to an unrelated HTTP error. I have launched the test suite again!

**Comment by aviau** [comment]
Hmm what is going on...

> OpenSSL: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
Unable to establish SSL connection.

**Comment by aviau** [comment]
I'll open a PR against your branch.

**Comment by babilen** [comment]
Feel free to fix them!

**Comment by aviau** [comment]
I'll merge this as it is a great improvement on what we had before.

Thank you for your time @babilen

**Comment by babilen** [comment]
You are welcome, let's see if we can tackle the remaining issues in due course.

**Pull request merged**
