### PR TITLE
chore(client_test): adding in an old test from legacy PR#315

### PR DESCRIPTION
**Pull request by sebito91**
This PR closes out a legacy PR #315 that is no longer maintained by the original author, @oldmantaiter. We shamelessly steal the tests and add them in here.

### CODE REVIEW

**Comment by aviau** [comment]
You seem to be missing the actual code!

**Comment by sebito91** [comment]
The code is already there, added somewhere since 2016 when the PR was first opened!

**Comment by aviau** [comment]
Ahhh! Alright then

**Comment by aviau** [comment]
:ship: :it:

**Comment by sebito91** [comment]
Working to clear out the backlog!

**Pull request merged**
