### PR TITLE
adding py35 and py36

### PR DESCRIPTION
**Pull request by sebito91**

### CODE REVIEW

**Comment by sebito91** [comment]
Given that we support up to py36 now, should we mark this as Beta instead of Alpha?

**Comment by aviau** [comment]
That is way too many envs builds. Can you please just leave the py35 and py36 envs, not coverage, flake8 and docs?

building docs on one interpreter is fine.

**Comment by sebito91** [comment]
Point taken, fixing now...

**Comment by aviau** [comment]
Looks good to me!

**Pull request merged**
