### PR TITLE
[WIP] add py37 and recent influxdb

### PR DESCRIPTION
**Pull request by clslgrnc**
+ diversify panda and numpy version

### CODE REVIEW

**Comment by clslgrnc** [comment]
It seems that a test fails with numpy > 1.13.1
I'll investigate later

**Comment by clslgrnc** [comment]
Here is the culprit:
```
>>> np.version.version
'1.13.3'
>>> a = np.float64('1.1111111111111')
>>> str(a)
'1.11111111111'
```
```
>>> np.version.version
'1.16.2'
>>> a = np.float64('1.1111111111111')
>>> str(a)
'1.1111111111111'
```

**Comment by clslgrnc** [comment]
I really do not know how to put python 3.7 into travis matrix.
An alternative would be to use xenial and sudo:true for all builds. What do you think?

**Comment by aviau** [comment]
> An alternative would be to use xenial and sudo:true for all builds. 

We should avoid doing that. Container builds are scheduled faster (I think) and going back to VMs would be a step backwards.

**Comment by aviau** [comment]
Thank you for the PR!

**Comment by clslgrnc** [comment]
This time you were too fast for me :wink: I pushed the doc and a small fix in #693.
(To your defense I was fiddling with the WIP status of the PR, I felt that travis was not starting fast enough)

**Pull request merged**
