### PR TITLE
Add CQs management methods to the client

### LINKED ISSUE #207: Does the python client support Continuous Queries?
Hi 

Does the python client for influxdb support Continuous Queries?

Thanks

### PR DESCRIPTION
**Pull request by lukaszdudek-silvair**
Duplicates #414 & fixes #207 .
Thanks to @smolse for providing this implementation!

### CODE REVIEW

**Comment by lukaszdudek-silvair** [comment]
The Travis build is affected by what has been described in #679 . Should I cherry-pick [this commit](https://github.com/influxdata/influxdb-python/pull/679/commits/5da62e9b57bb5653d73ee48a32eb7c6802ce31d4) or wait for that PR to be merged?

**Comment by clslgrnc** [comment]
You will have to take all of #679 and modify your docstrings (see [failed PEP257](https://travis-ci.org/influxdata/influxdb-python/jobs/500387005)) to pass CI.

**Comment by lukaszdudek-silvair** [comment]
This PR is ready to be reviewed.

**Comment by xginn8** [comment]
thanks for contributing to the project @lukaszdudek-silvair, I will review this in the next few days

**Comment by shr00mie** [comment]
i don't think in my entire github history have i come searching for a feature request or its progress in issues to find that it's been PR'd within the last couple weeks to have it potentially implemented so imminently. the ability to create retention policies without the corresponding CQs seemed like a strange choice.

i too would very much enjoy this getting added as soon as time allows.

thanks, @lukaszdudek-silvair for the legwork on this. looking forward to the polished version.

**Comment by shr00mie** [comment]
*slow clap*

**Comment by xginn8** [comment]
@lukaszdudek-silvair thank you for contributing!!

**Pull request merged**
