### PR TITLE
Fix chunked query to return chunk resultsets

### LINKED ISSUE #531: Out of memory error when querying large data set with chunked=True
Making large queries for very large result sets results in out of memory errors.  This can be traced back to the function _read_chunked_response in client.py which reads the entire response into RAM before returning a ResultSet.

### PR DESCRIPTION
**Pull request by hrbonz**
When querying large data sets, it's vital to get a chunked responses to manage memory usage. Wrapping the query response in a generator and streaming the request provides the desired result.
It also fixes `InfluxDBClient.query()` behavior for chunked queries that is currently not working according to [specs](https://github.com/influxdata/influxdb-python/blob/master/influxdb/client.py#L429)

close #585
close #531
close #538

### CODE REVIEW

**Comment by hrbonz** [comment]
I'm currently running tox tests and will fix whatever fails in travisCI

**Comment by psy0rz** [comment]
Does this also close https://github.com/influxdata/influxdb-python/pull/538 ?

**Comment by hrbonz** [comment]
Yes, it covers it as well. I've had issues with my laptop so got caught in a bit of a snag, will get back to fixing the tests.
The tests were designed to pass rather than reflect the method documented behavior.

**Comment by hrbonz** [comment]
I had to change the test substantially as it was testing a broken behavior not the documented (and better one imho).
I'm testing that I'm getting the proper number of chunked `ResultSet`s and testing that each `Resultset` returns the proper elements.

**Comment by hrbonz** [comment]
On a side note, I've been using this code to move data from an old version of influxdb to another (and doing some type casting in the middle) with no issue. About 50G of data across 1500 measurements.

**Comment by russorat** [comment]
@hrbonz Thank you!  i've reached out to @sebito91 to take a look.

**Comment by hrbonz** [comment]
Thanks @russorat, hopefully this PR is getting some attention while the new library is getting all the love ;)

**Comment by hrbonz** [comment]
@sebito91 quite happy to see it finally done and merged! Now to 

ping @psy0rz for the inspiration

**Comment by psy0rz** [comment]
awesome! thank YOU for actually implementing it all the way :)

**Pull request merged**
