### PR TITLE
Support streamed chunking (fixing #531 and others)

### LINKED ISSUE #531: Out of memory error when querying large data set with chunked=True
Making large queries for very large result sets results in out of memory errors.  This can be traced back to the function _read_chunked_response in client.py which reads the entire response into RAM before returning a ResultSet.

### PR DESCRIPTION
**Pull request by psy0rz**
query() will now return a generator of ResultSets instead of a list when setting chunked=True. This might be backwards incompatible, but seems to be the only reason one might even use chunked mode?

Another reason to use chunked mode could be that the server enforces it, but then again: If results are that big, wouldn't you want a generator as well?

### CODE REVIEW

**Comment by psy0rz** [comment]
i'll try to fix the test as well

**Comment by psy0rz** [comment]
I think it would be cleaner to add a "stream" parameter to get a streaming response. This way we wont breakn compatibility. Perhaps there are also some usecases where someone wants to autonagically combine a chunked result in memory, like it is currently working.

**Comment by psy0rz** [comment]
All set and done now. there a new stream parameter to support "streamed chunking". this is usefull for very large result sets. (trying to traverse and anaylse over 20 million+ results here) Also updated/added documentation in the sourcecode.

related project: https://github.com/psy0rz/meowton

**Comment by xginn8** [comment]
@psy0rz thank you for the patch! would you mind adding a test to this PR?

**Comment by psy0rz** [comment]
Ok will do that soonish..

**Comment by joaopcbertoldo** [comment]
Hi, I believe that someone forgot to actually resolve the conflicts.

@xginn8 do you mind finishing this merge PR?

**Comment by psy0rz** [comment]
also i dont have time to add the requested regressions tests.

**Comment by aviau** [comment]
If the author does not have the time to finish the PR then someone has to pick it up. I'll close this one and merge the other, if it is complete and includes tests.

**Comment by psy0rz** [comment]
"Potentially break the api" ;) Dont worry you can be harsh, I would apply the same policy in your case.

**Comment by aviau** [comment]
I had picked that up from your initial comment saying it could be backwards incompatiblte but this is not t he case due to the steam parameter, is it?

**Comment by psy0rz** [comment]
yes, but still i could have made a mistake :)

**Comment by pedrofaria09** [comment]
Any solution for this? returning a query with millions of rows will affect memory badly.

**Comment by xiandong79** [comment]
returning a query with millions of rows is still impossible on 2019-08-01. @pedrofaria09 @aviau

**Pull request closed without merging**
