### PR TITLE
add custom timestamp to SeriesHelper

### PR DESCRIPTION
**Pull request by areski**

### CODE REVIEW

**Comment by ReAzem** [comment]
I don't think that this is the most intuitive way to do this. Why not just always accept the timestamp parameter when creating new points?

A simple kwargs pop could be done at [helper.py#L105](https://github.com/areski/influxdb-python/blob/fix-timeseries-timestamp/influxdb/helper.py#L105).

**Comment by areski** [comment]
if you do so there then the 'cls._datapoints' will not be set correctly, this will fail:
cls._datapoints[cls._series_name.format(**kw)].append(cls._type(**kw))

**Comment by ReAzem** [comment]
Sorry for the long delay :(

 I have been busy with the ResultSet. I'll get to this soon!

**Comment by areski** [comment]
no worries ;)

**Comment by gst** [comment]
@areski 
there is a minor flake8 issue : 

influxdb/helper.py:147:80: E501 line too long (81 > 79 characters)

are you still around there to complete entirely this PR ? :)

**Comment by areski** [comment]
@gst here a fix for the flake8 issue

Can you be more specific about what you mean by completing *entirely* the PR?

**Comment by gst** [comment]
> Can you be more specific about what you mean by completing entirely the PR?

nothing more, or yes if not already done : if you can rebase your branch on top of master and update the pr ?
also @aviau will have to look on this as I don't know how it's still needed ..

**Comment by areski** [comment]
Let's see if @aviau wants this in, no point we work on this if it's not needed ;)

**Comment by gst** [comment]
right ;)
let's wait & see..

**Comment by aviau** [comment]
Can we have a tests? I'll merge after.

**Comment by aviau** [comment]
@areski Do you want to finish this PR, or should we take over? 

Todo:
 - Add tests
 - Change ```timestamp``` to ```time```
 - Add a time to each point when time is not specified.

The reason we should add a time when it is not specified is explained by #264. Inserting several points with no time will result in only the last being taken.

**Comment by matt-snider** [comment]
Hi is this PR still going to be developed and merged? This feature would be very useful to us so that we can use a high batch size, while still retaining good time resolution (and not losing any points).

**Comment by aviau** [comment]
@matt-snider Would you like to take over?

**Comment by matt-snider** [comment]
Sorry for the late response. 

I will take a look at this and open up another PR when I get some time.

**Comment by aviau** [comment]
I'll close this as @matt-snider's PR was merged

**Pull request closed without merging**
